<div class="zp_box"><a href="[field:arcurl/]" class="zp_boxfc" onmouseover="Showtit([field:global name=autoindex runphp="yes"]@me[/field:global])" onmouseout="Hiddentit([field:global name=autoindex runphp="yes"]@me[/field:global])"></a>
      <div class="picbox">
        <div class="pop_tit" id="zp[field:global name=autoindex runphp="yes"]@me[/field:global]"><span class="p_tit1" title="[field:title/]">[field:title/]</span><br />
          <span class="p_tit2">[field:title/]</span></div>
        <img src='[field:litpic/]' alt='[field:title function='html2text(@me)'/]'/></div>
    </div>