<?php
$z[0]=Array("include","",0,34);
$z[0][4]['filename']="top.htm";
$z[1]=Array("field","",883,912);
$z[1][4]['name']="position";
$z[2]=Array("field","",921,940);
$z[2][4]['name']="title";
$z[3]=Array("field","",1311,1330);
$z[3][4]['name']="title";
$z[4]=Array("field","",1479,1498);
$z[4][4]['name']="title";
$z[5]=Array("field","",1610,1629);
$z[5][4]['name']="title";
$z[6]=Array("field","",1663,1719);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[7]=Array("field","",1753,1773);
$z[7][4]['name']="writer";
$z[8]=Array("field","",1830,1855);
$z[8][4]['name']="description";
$z[9]=Array("field","",1952,1970);
$z[9][4]['name']="body";
$z[10]=Array("include","",2116,2153);
$z[10][4]['filename']="footer.htm";

?>