<?php
$z[0]=Array("include","",0,34);
$z[0][4]['filename']="top.htm";
$z[1]=Array("channel","\r\n     <a href=\"[field:typelink/]\" title=\"[field:typename/]\" onClick=\"Changmenu([field:global name=autoindex runphp=\"yes\"]@me[/field:global])\" id=\"zpmenu1\">[field:typename/]</a> \r\n ",1678,1899);
$z[1][4]['type']="son";
$z[2]=Array("list","\r\n   <div class=\"zp_box\"><a href=\"[field:arcurl/]\" class=\"zp_boxfc\" onmouseover=\"Showtit([field:global name=autoindex runphp=\"yes\"]@me[/field:global])\" onmouseout=\"Hiddentit([field:global name=autoindex runphp=\"yes\"]@me[/field:global])\"></a>\r\n      <div class=\"picbox\">\r\n        <div class=\"pop_tit\" id=\"zp[field:global name=autoindex runphp=\"yes\"]@me[/field:global]\"><span class=\"p_tit1\" title=\"[field:title/]\">[field:title/]</span><br />\r\n          <span class=\"p_tit2\">[field:title/]</span></div>\r\n        <img src='[field:litpic/]' alt='[field:title function='html2text(@me)'/]'/></div>\r\n    </div>\r\n",2152,2814);
$z[2][4]['row']="9";
$z[2][4]['pagesize']="9";
$z[2][4]['titlelen']="30";
$z[3]=Array("pagelist","",2999,3070);
$z[3][4]['listitem']="info,index,end,pre,next,pageno";
$z[3][4]['listsize']="5";
$z[4]=Array("include","",3227,3264);
$z[4][4]['filename']="footer.htm";

?>